name: Test - PR

on: pull_request

jobs:
  build_test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Build
        run: npm install
      - name: Install runtime
        run: npm run install-runtime
      - name: Lint
        run: npm run lint
      - name: Test
        run: script --quiet --return -c "npm run test" /dev/null
      - name: Copy&Paste detection
        run: npm run cpd
      - name: Bundle
        run: npm run bundle
      - name: Archive blacksmith artifact
        uses: actions/upload-artifact@v2
        with:
          name: blacksmith-linux-x64.tar.gz
          path: artifacts/build/blacksmith-linux-x64.tar.gz
